from typing import Optional

class BitVector:
    def __init__(self, bits: list[bool]) -> None: ...
    def rank(self, i: int) -> int: ...
    def select(self, k: int) -> Optional[int]: ...
    def get(self, i: int) -> bool: ...
    def count_ones(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> bool: ...
    def __repr__(self) -> str: ...

class EliasFano:
    def __init__(self, values: list[int]) -> None: ...
    def get(self, i: int) -> int: ...
    def contains(self, value: int) -> bool: ...
    def len(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, value: int) -> bool: ...
    def __getitem__(self, i: int) -> int: ...
    def __repr__(self) -> str: ...

class WaveletTree:
    def __init__(self, data: list[int], sigma: int) -> None: ...
    def rank(self, symbol: int, i: int) -> int: ...
    def select(self, symbol: int, k: int) -> Optional[int]: ...
    def access(self, i: int) -> int: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
